#!/bin/bash

[ ! -d /tmp/LS_COLORS ] && \
  mkdir /tmp/LS_COLORS && \
  curl -L https://api.github.com/repos/trapd00r/LS_COLORS/tarball/master | tar xzf - --directory=/tmp/LS_COLORS --strip=1 && \
  ( cd /tmp/LS_COLORS && sh install.sh );

cd $(dirname $0);
[ ! -f ~/.git-prompt.sh ] && wget -O ~/.git-prompt.sh https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh
[ -f ~/.bashrc ] && mv -n ~/.bashrc ~/.bashrc.bak

cp .bashrc ~;
source ~/.bashrc;
